name: Tests

on: push

permissions: read-all

env:
  SOL_AST_COMPILER_CACHE: ${{ github.workspace }}/.compiler_cache

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Solc AST binary
      run: yarn global add solc-typed-ast

    - name: Install dependencies
      run: yarn install

    - name: Pre-download compilers from historical builds archive
      run: |
        sol-ast-compile --download-compilers native wasm
        find $SOL_AST_COMPILER_CACHE -name 'list.json' -delete
        find $SOL_AST_COMPILER_CACHE -name '*v0.5.17*' -delete

    - name: Run tests
      run: yarn test
